# Generated by Django 3.1.7 on 2021-05-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ft_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jméno')),
            ],
            options={
                'verbose_name': 'Spolupracující',
                'verbose_name_plural': 'Spolupracující',
            },
        ),
        migrations.CreateModel(
            name='ft_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název města')),
                ('region', models.CharField(choices=[('JČ', 'Jihočeský'), ('PLZ', 'Plzeňský'), ('KAR', 'Karlovarský'), ('LIB', 'Liberecký'), ('STŘ', 'Středočeský a Praha'), ('KHD', 'Královehradecký'), ('JHM', 'Jihomoravský'), ('VYS', 'Vysočina'), ('ÚST', 'Ústecký'), ('PAR', 'Pardubický'), ('OLM', 'Olomoucký'), ('ZLN', 'Zlínský'), ('MSZ', 'Moravskoslezský')], max_length=20, verbose_name='Kraj')),
            ],
            options={
                'verbose_name': 'Místo',
                'verbose_name_plural': 'Místa',
            },
        ),
        migrations.CreateModel(
            name='ft_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ft_Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=30, verbose_name='Příjmení')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1, verbose_name='Pohlaví')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Uživatelské jméno')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefonní číslo')),
                ('bank_account_number', models.CharField(default='123456/9999', max_length=100, verbose_name='Číslo účtu')),
            ],
            options={
                'verbose_name': 'Vrtač',
                'verbose_name_plural': 'Vratči',
            },
        ),
        migrations.CreateModel(
            name='ft_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název akce')),
                ('total_meters', models.FloatField(verbose_name='Metrů čtverečních celkem')),
                ('company_worked_with', models.ManyToManyField(to='main.ft_Company', verbose_name='Spolupracující')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.ft_place', verbose_name='Místo')),
                ('workers', models.ManyToManyField(to='main.ft_Worker', verbose_name='Vrtači')),
            ],
            options={
                'verbose_name': 'Akce',
                'verbose_name_plural': 'Akce',
            },
        ),
    ]
