# Generated by Django 3.1.7 on 2021-05-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ft_event_czk_per_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ft_worker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
