# Generated by Django 3.1.7 on 2021-05-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210529_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ft_event',
            name='company_worked_with',
            field=models.ManyToManyField(blank=True, to='main.ft_Company', verbose_name='Spolupracující'),
        ),
        migrations.AlterField(
            model_name='ft_event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.ft_place', verbose_name='Místo'),
        ),
        migrations.AlterField(
            model_name='ft_event',
            name='total_meters',
            field=models.FloatField(blank=True, null=True, verbose_name='Metrů čtverečních celkem'),
        ),
        migrations.AlterField(
            model_name='ft_event',
            name='workers',
            field=models.ManyToManyField(blank=True, to='main.ft_Worker', verbose_name='Vrtači'),
        ),
        migrations.AlterField(
            model_name='ft_worker',
            name='bank_account_number',
            field=models.CharField(blank=True, default='123456/9999', max_length=100, verbose_name='Číslo účtu'),
        ),
    ]
