# Generated by Django 3.1.7 on 2021-05-16 17:04

from django.db import migrations, models
import django.db.models.deletion
import places.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ft_MyLocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', places.fields.PlacesField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ft_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ft_Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ft_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('last_edited', models.DateTimeField(auto_now=True, verbose_name='')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('total_meters', models.FloatField(verbose_name='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ft_user', verbose_name='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ft_mylocationmodel', verbose_name='')),
                ('workers', models.ManyToManyField(to='main.ft_Worker', verbose_name='')),
            ],
        ),
    ]
