# Generated by Django 3.1.7 on 2021-05-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ft_event',
            name='photos',
        ),
    ]
