# Generated by Django 3.1.7 on 2021-05-30 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_ft_event_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ft_company',
            options={'ordering': ['name'], 'verbose_name': 'Spolupracující', 'verbose_name_plural': 'Spolupracující'},
        ),
        migrations.AlterModelOptions(
            name='ft_event',
            options={'ordering': ['total_meters', 'place', 'name'], 'verbose_name': 'Akce', 'verbose_name_plural': 'Akce'},
        ),
        migrations.AlterModelOptions(
            name='ft_place',
            options={'ordering': ['region', 'name'], 'verbose_name': 'Místo', 'verbose_name_plural': 'Místa'},
        ),
        migrations.AddField(
            model_name='ft_event',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
