# Generated by Django 3.1.7 on 2021-05-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210530_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='ft_worker',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození'),
        ),
        migrations.AddField(
            model_name='ft_worker',
            name='social_security_number',
            field=models.CharField(blank=True, default='rodne/cislo', max_length=30, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='ft_worker',
            name='bank_account_number',
            field=models.CharField(blank=True, default='cislo/uctu', max_length=100, verbose_name='Číslo účtu'),
        ),
    ]
