# Generated by Django 3.1.7 on 2021-05-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210530_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ft_upcoming_event',
            options={'ordering': ['name'], 'verbose_name': '\nNadcházející akce', 'verbose_name_plural': '\nNadcházející akce'},
        ),
        migrations.AlterModelOptions(
            name='ft_worker',
            options={'verbose_name': '\nVrtač', 'verbose_name_plural': '\nVrtači'},
        ),
    ]
