# Generated by Django 3.1.7 on 2021-05-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210530_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ft_worker',
            name='password',
            field=models.CharField(default='', max_length=15, verbose_name='Heslo'),
        ),
    ]
