# Generated by Django 3.1.7 on 2021-05-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210530_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ft_worker',
            name='password',
            field=models.CharField(blank=True, default='xzex', max_length=15, verbose_name='Heslo'),
        ),
    ]
