# Generated by Django 3.1.7 on 2021-06-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210530_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='ft_upcoming_event',
            name='end_day',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ft_upcoming_event',
            name='end_month',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ft_upcoming_event',
            name='start_day',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ft_upcoming_event',
            name='start_month',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ft_upcoming_event',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='ft_worker',
            name='password',
            field=models.CharField(blank=True, default='xoup', max_length=15, verbose_name='Heslo'),
        ),
    ]
