# Generated by Django 3.1.7 on 2021-06-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210602_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='ft_worker',
            name='display_name',
            field=models.CharField(default='', max_length=30, verbose_name='Zobrazovací Jméno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ft_upcoming_event',
            name='total_meters',
            field=models.IntegerField(blank=True, null=True, verbose_name='Metrů čtverečních celkem'),
        ),
        migrations.AlterField(
            model_name='ft_worker',
            name='password',
            field=models.CharField(blank=True, default='ylxk', max_length=15, verbose_name='Heslo'),
        ),
    ]
