# Generated by Django 3.1.7 on 2021-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210602_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ft_upcoming_event',
            name='workers_required',
            field=models.IntegerField(blank=True, verbose_name='Vrtačů potřeba'),
        ),
        migrations.AlterField(
            model_name='ft_worker',
            name='password',
            field=models.CharField(blank=True, default='xsio', max_length=15, verbose_name='Heslo'),
        ),
    ]
