# Generated by Django 3.1.7 on 2021-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210602_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='ft_upcoming_event',
            name='year',
            field=models.IntegerField(blank=True, default=2021, null=True, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='ft_upcoming_event',
            name='start_month',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Měsíc'),
        ),
        migrations.AlterField(
            model_name='ft_worker',
            name='password',
            field=models.CharField(blank=True, default='dbje', max_length=15, verbose_name='Heslo'),
        ),
    ]
