# Generated by Django 3.1.7 on 2021-06-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210602_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='ft_worker',
            name='power',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='ft_worker',
            name='password',
            field=models.CharField(blank=True, default='ccrk', max_length=15, verbose_name='Heslo'),
        ),
    ]
