# Generated by Django 3.1.7 on 2021-06-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210603_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ft_worker',
            name='password',
            field=models.CharField(blank=True, default='krrz', max_length=15, verbose_name='Heslo'),
        ),
    ]
